# Generated by Django 6.0.1 on 2026-03-01 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audio',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('publicada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'historias',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id_nodo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_nodo', models.CharField(blank=True, max_length=150, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('es_final', models.BooleanField(default=False)),
                ('audio_fondo', models.ForeignKey(blank=True, db_column='id_audio_fondo', null=True, on_delete=django.db.models.deletion.CASCADE, to='novela.audio')),
                ('historia', models.ForeignKey(db_column='id_historia', on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='novela.historia')),
                ('imagen_escenario', models.ForeignKey(blank=True, db_column='id_imagen_escenario', null=True, on_delete=django.db.models.deletion.CASCADE, to='novela.imagen')),
            ],
            options={
                'db_table': 'nodos',
            },
        ),
        migrations.AddField(
            model_name='historia',
            name='nodo_inicio',
            field=models.ForeignKey(blank=True, db_column='id_nodo_inicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_inicio_de', to='novela.nodo'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('texto_opcion', models.CharField(max_length=255)),
                ('nodo_destino', models.ForeignKey(db_column='id_nodo_destino', on_delete=django.db.models.deletion.CASCADE, related_name='opciones_destino', to='novela.nodo')),
                ('nodo_origen', models.ForeignKey(db_column='id_nodo_origen', on_delete=django.db.models.deletion.CASCADE, related_name='opciones_origen', to='novela.nodo')),
            ],
            options={
                'db_table': 'opciones',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('historia', models.ForeignKey(db_column='id_historia', on_delete=django.db.models.deletion.CASCADE, to='novela.historia')),
                ('imagen', models.ForeignKey(db_column='id_imagen', on_delete=django.db.models.deletion.CASCADE, to='novela.imagen')),
            ],
            options={
                'db_table': 'personajes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='novela.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('historia', models.ForeignKey(db_column='id_historia', on_delete=django.db.models.deletion.CASCADE, to='novela.historia')),
                ('nodo_actual', models.ForeignKey(db_column='id_nodo_actual', on_delete=django.db.models.deletion.CASCADE, to='novela.nodo')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='novela.usuario')),
            ],
            options={
                'db_table': 'progreso_usuario',
            },
        ),
        migrations.AddField(
            model_name='historia',
            name='creador',
            field=models.ForeignKey(db_column='id_creador', on_delete=django.db.models.deletion.CASCADE, to='novela.usuario'),
        ),
        migrations.CreateModel(
            name='NodoPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=50)),
                ('nodo', models.ForeignKey(db_column='id_nodo', on_delete=django.db.models.deletion.CASCADE, to='novela.nodo')),
                ('personaje', models.ForeignKey(db_column='id_personaje', on_delete=django.db.models.deletion.CASCADE, to='novela.personaje')),
            ],
            options={
                'db_table': 'nodo_personaje',
                'unique_together': {('nodo', 'personaje')},
            },
        ),
    ]
